-- Messagerie (chat) rattachée à une demande de contact.
--
-- Modèle : le locataire crée une `Demandes_Contact` ; le proprietaire l'accepte
-- (`contact_etabli = true`) ; à partir de là les deux parties peuvent échanger
-- des messages dans ce fil. Une demande = un fil de discussion.
--
-- ⚠️ Choix de conception (perf realtime) : `sender_id`/`recipient_id` sont
-- **dénormalisés** sur la ligne pour que la politique **SELECT** soit
-- `auth.uid() IN (sender_id, recipient_id)` — simple et indexée. C'est cette
-- politique qu'évalue `realtime.list_changes` à chaque événement : une RLS avec
-- sous-requête (jointure vers Demandes_Contact → Immeubles) y coûterait cher et
-- a déjà gelé le web par le passé (cf. RealtimeService). La vérification lourde
-- (« la demande est-elle acceptée et suis-je bien partie prenante ? ») est faite
-- **à l'INSERT uniquement**, où le coût est négligeable.

create table if not exists public."Messages" (
  id            bigint generated by default as identity primary key,
  demande_id    bigint not null references public."Demandes_Contact"(id) on delete cascade,
  -- FK vers Users_Client (et non auth.users) : c'est la convention du projet et
  -- c'est ce qui rend l'embed PostgREST possible
  -- (`sender:Users_Client!sender_id(full_name)`).
  sender_id     uuid   not null references public."Users_Client"(id) on delete cascade,
  recipient_id  uuid   not null references public."Users_Client"(id) on delete cascade,
  body          text   not null check (length(btrim(body)) between 1 and 4000),
  created_at    timestamptz not null default now(),
  read_at       timestamptz
);

-- Index au service des politiques + des écrans (fil trié, compteur non lus).
create index if not exists messages_demande_created_idx
  on public."Messages" (demande_id, created_at);
create index if not exists messages_recipient_unread_idx
  on public."Messages" (recipient_id) where read_at is null;
create index if not exists messages_sender_idx
  on public."Messages" (sender_id);

alter table public."Messages" enable row level security;

-- Participant d'une demande : le locataire, ou le proprietaire de l'immeuble.
-- SECURITY DEFINER pour ne pas dépendre de la RLS de Demandes_Contact/Immeubles.
create or replace function public.can_access_demande(p_demande_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
      from public."Demandes_Contact" d
      left join public."Immeubles" i on i.id = d.immeuble_id
     where d.id = p_demande_id
       and (d.locataire_id = auth.uid() or i.owner_id = auth.uid())
  );
$$;

revoke execute on function public.can_access_demande(bigint) from public, anon;
grant execute on function public.can_access_demande(bigint) to authenticated;

-- La demande est-elle acceptée (le fil est-il ouvert) ?
create or replace function public.demande_est_acceptee(p_demande_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select d.contact_etabli from public."Demandes_Contact" d where d.id = p_demande_id),
    false
  );
$$;

revoke execute on function public.demande_est_acceptee(bigint) from public, anon;
grant execute on function public.demande_est_acceptee(bigint) to authenticated;

-- SELECT : volontairement trivial (voir l'entête) — pas de sous-requête.
create policy participant_select_messages on public."Messages"
  for select to authenticated
  using (auth.uid() = sender_id or auth.uid() = recipient_id);

-- INSERT : on ne peut écrire qu'en son propre nom, dans un fil dont on est
-- partie prenante, et seulement une fois la demande acceptée.
create policy participant_insert_messages on public."Messages"
  for insert to authenticated
  with check (
    sender_id = auth.uid()
    and recipient_id <> auth.uid()
    and public.can_access_demande(demande_id)
    and public.demande_est_acceptee(demande_id)
  );

-- UPDATE : réservé au destinataire, et uniquement pour marquer « lu »
-- (le garde-fou sur les colonnes est le trigger ci-dessous).
create policy recipient_update_messages on public."Messages"
  for update to authenticated
  using (recipient_id = auth.uid())
  with check (recipient_id = auth.uid());

-- On n'édite ni ne réécrit un message : seul `read_at` peut bouger.
create or replace function public.messages_only_read_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.body is distinct from old.body
     or new.sender_id is distinct from old.sender_id
     or new.recipient_id is distinct from old.recipient_id
     or new.demande_id is distinct from old.demande_id
     or new.created_at is distinct from old.created_at then
    raise exception 'Seul read_at peut être modifié sur un message';
  end if;
  return new;
end;
$$;

-- Fonction interne (trigger) : pas appelable en RPC (cf. la migration
-- revoke_execute_internal_functions — même convention).
revoke execute on function public.messages_only_read_at() from public, anon, authenticated;

drop trigger if exists trg_messages_only_read_at on public."Messages";
create trigger trg_messages_only_read_at
  before update on public."Messages"
  for each row execute function public.messages_only_read_at();

-- DELETE : l'expéditeur peut retirer son propre message.
create policy sender_delete_messages on public."Messages"
  for delete to authenticated
  using (sender_id = auth.uid());

-- Realtime : RLS SELECT triviale + indexée → publication sûre (cf. entête).
alter publication supabase_realtime add table public."Messages";
